### ISSUE TITLE
build mes problem

### ISSUE THREAD

**Issue by zh1314** [qcadoo/mes#13]
hi, i try to build mes according https://qcadoo.atlassian.net/wiki/display/QCDMESDOC/Building+MES+from+source+code+-+tutorial document, but when i build the last repository mes, it failed and the information is below.please help me to resolve these error, thank you very much.

[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'dependencies.dependency.systemPath' for postgresql:postgresql:jar:jdbc4 should not point at files within the project directory, ${basedir}/driver/postgresql-9.4.1212.jar will be unresolvable by dependent projects @ com.qcadoo.mes:mes-application:[unknown-version], /Users/zhanghui/skye.git/qcadoo/mes/mes-application/pom.xml, line 303, column 25
[ERROR] 'build.plugins.plugin.version' for org.mortbay.jetty:maven-jetty-plugin must be a valid version but is '${jetty.version}'. @ com.qcadoo.mes:mes-application:[unknown-version], /Users/zhanghui/skye.git/qcadoo/mes/mes-application/pom.xml, line 341, column 26
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.qcadoo.mes:mes-application:1.5-SNAPSHOT (/Users/zhanghui/skye.git/qcadoo/mes/mes-application/pom.xml) has 1 error
[ERROR]     'build.plugins.plugin.version' for org.mortbay.jetty:maven-jetty-plugin must be a valid version but is '${jetty.version}'. @ com.qcadoo.mes:mes-application:[unknown-version], /Users/zhanghui/skye.git/qcadoo/mes/mes-application/pom.xml, line 341, column 26
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by lponiewierski** [comment]
Hi, 
this problem will be fixed in another version, which will be released next week.
If You don't want to wait please checkout to tag 1.7.3.
Regards.

**Comment by zh1314** [comment]
Thank you for your answer, 
I checkout to tag 1.7.3 as you said, it build successfully. but when i navigate to mes/mes-application and execute command 'mvn clean install -o -Ptomcat -Dprofile=tomcat', it failed and the information is below, then i tried to change the db.properties as the document said, but i can't find the folder 'tomcat-archiver' in mes/mes-application/target/, sorry for trouble you.

[ERROR] Plugin org.apache.maven.plugins:maven-antrun-plugin:1.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-antrun-plugin:jar:1.5: Cannot access qcadoo-releases-plugin-repository (http://nexus.qcadoo.org/content/repositories/releases) in offline mode and the artifact org.apache.maven:maven-parent:pom:16 has not been downloaded from it before. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

**Comment by lponiewierski** [comment]
Try without -o.

**Comment by zh1314** [comment]
Oh, You are right, i am so careless, Thank you very much.😁
