### ISSUE TITLE
import projects to eclipse

### ISSUE THREAD

**Issue by zh1314** [qcadoo/mes#14]
hi,
i want to import projects in eclipse, but i don't know how to import, because there are four projects. 
and how can i run this project with tomcat in eclipse instead of tomcat script such as startup.sh.

i don't know if my thought is right:
the mes's view is made up by plugins in qcadoo project?

if there have some documents to introduce the communication between these four projects and every project's direction structure.

maybe my question is so stupid, sorry for that, please help me. 
thank you very much.

**Comment by zh1314** [comment]
about my question, i have some new comprehension.

1.the qcadoo-super-pom-open is the parent of remain there projects, that can be extended by qcadoo-maven-plugin, qcadoo and mes, all right?
2.the qcadoo-maven-plugin is a project that you write a maven plugin by yourself, right?
3.the qcadoo is a project that defined qcadoo application's framework by plugins format, contains some system functions, such as security, mail ,view management and so on, right?
4.the mes is the core, mes-plugins defined the main view that you can see in application, and the mes-application dependency the mes-plugins to deploy war that can run in tomcat, right?
5.so if i want to run qcadoo by eclipse, i can import mes-application in eclipse?  and if i want to modify the function i can import the plugin of mes-plugins? and if i want to add some functions, i can add a mes-plugin in mes-plugins? right?

sorry, my questions is too long.
please help me answer me.
thank you~~~~

**Comment by marcinperlak** [comment]
Please have a look at our wiki page regarding development questions : https://qcadoo.atlassian.net/wiki/spaces/QCDMESDOC/pages/3375136/Getting+started+with+development

**Comment by zh1314** [comment]
hi，
can i execute tomcat:run to run mes-application in eclipse?

**Comment by lponiewierski** [comment]
Hi,
we don't use Eclipse in our work.
Sorry but we can't help You.
Regards.
