### ISSUE TITLE
running Maven issues

### ISSUE THREAD

**Issue by iCubed4-RonLee** [qcadoo/mes#15]
i got to the \mes\mes-application\ folder and I run the following command:
mvn clean install -Ptomcat -Dprofile=package

i generate a package to release on my server but I get the following error:
=======================================================
root@Dev:~/mes-application_170720/bin# sh startup.sh
: not found 2: startup.sh:
: not found 17: startup.sh:
: not found 21: startup.sh:
startup.sh: 24: startup.sh: Syntax error: word unexpected (expecting "in")
=======================================================

but if I drop in the files from the pre-compiled version 1.7.5 i am able to run the startup.sh properly.
this tells me there is something wrong with my build.

I have resynced my git for the 4 folders and I have reran all builds in the following orders:
a)  /qcadoo/qcadoo-super-pom-open/mvn clean install
b)  /qcadoo/qcadoo-maven-plugin/mvn clean install
c)  /qcadoo/qcadoo/mvn clean install -DskipTests
d)  /qcadoo/mes/mvn clean install -DskipTests
e) /qcadoo/mes/mes-application/mvn clean install -Ptomcat -Dprofile=package

let me know what I am doing wrong here...
the following steps were all tested under Win10, Ubuntu12 and Ubuntu17

hopefully someone can help...

**Comment by lponiewierski** [comment]
Hi,
please check if this help:
`chmod +x *.sh `
in tomcat bin directory.
Regards.

**Comment by iCubed4-RonLee** [comment]
hi Łukasz ,


already tried that.  this is what I've done:

- chmod +x:   for all .sh files

- chmod 777:   for all .sh files

- chmod 777: for the whole /bin folder


here is one procedure that worked, after rebuilding the code by running the following:

\git\mes\mes-application> mvn clean install -Ptomcat -Dprofile=tomcat


go to the target folder:

D:\git\mes\mes-application\target\tomcat-archiver\mes-application\bin


and I copy the bin folder from your 1.7.5 Pre-Compiled Release package over to my targeted bin folder and then I am able to run.

I do notice that also there is missing catalina.sh file in our created folder.


is it possible there is a problem in compiling the /bin folder from the maven script?


Ron







Ron


________________________________

**Comment by lponiewierski** [comment]
Hi,
I've checked everything from the start on Windows 7 and all looks fine.
Application starts without any errors.

Could You check if You've got mes-application.zip package in your mes/mes-application/target folder?
If yes, please unzip it and check if there are *.sh files in the bin folder?
If yes, please try running application from this package.

**Comment by iCubed4-RonLee** [comment]
investigating and trying to redo the environment again.


will get back to you next week


Ron



________________________________
