### ISSUE TITLE
How can I access the Organize, Technologies...pages?

### ISSUE THREAD

**Issue by userjia** [qcadoo/mes#16]
I build mes success by the tutorial <Building MES from source code - tutorial>.
But the Organize...functions can't be accessed.

**Comment by userjia** [comment]
main.html#/dashboard.html page can't access Organize and the other two functions, why does this happen?T_T

**Comment by userjia** [comment]
Wait, I just pulled dev but didn't checkout

**Comment by lponiewierski** [comment]
Hi,
probably you don't have any roles assigned to user's access group.
Please log as superadmin user, then in the menu you should see Administration / Groups option.
Select the group your user is assigned to and add roles which to you want to have access.
Next relog as your user and you should see missing menu options.
Regards.

**Comment by userjia** [comment]
Thank you!
