### ISSUE TITLE
Time fields orders problem

### ISSUE THREAD

**Issue by semirov** [qcadoo/mes#17]
After saving the main order, the production order, in all fields containing time it takes one hour

for example - Created, but not saved, the master order: 
![image](https://user-images.githubusercontent.com/23023531/29066179-1bb60ba4-7c37-11e7-9f1c-30134b255478.png)

after save - 1 hour in all time fields

![image](https://user-images.githubusercontent.com/23023531/29066279-6d2aecac-7c37-11e7-9620-db43bc01e197.png)

![image](https://user-images.githubusercontent.com/23023531/29066333-9235954c-7c37-11e7-8a23-3312d116ebd9.png)

Build the latest master version

upd:

The time fields behave unstably, even in the approved order, the primary time is changed

**Comment by lponiewierski** [comment]
Hi,
I've just tested and can't reproduce this problem.
Could you give me some additional information?

Please check the time values in _masterorders_masterorder_ table in database:

`SELECT deadline, startdate, finishdate, dateofreceipt FROM masterorders_masterorder;`

What's the database time zone:

`SHOW time zone;`

Please check if the database time is different from current time:

`SELECT NOW();`

Regards.

**Comment by semirov** [comment]
Thanks for the answer.

Here is what returns the query:

`SELECT deadline, startdate, finishdate, dateofreceipt FROM masterorders_masterorder;`

![image](https://user-images.githubusercontent.com/23023531/29078772-01fc73c4-7c64-11e7-8831-ad45124084a6.png)

`SHOW time zone;`

![image](https://user-images.githubusercontent.com/23023531/29078836-262fa266-7c64-11e7-9e80-ce3343e0217a.png)

`SELECT now();`

![image](https://user-images.githubusercontent.com/23023531/29078855-346971ea-7c64-11e7-8ea3-e4abec455f34.png)

The system time is the same as the base time

**Comment by lponiewierski** [comment]
Do the same dates appear in the application?

**Comment by semirov** [comment]
Yes, the dates coincide, each time you click the button to save the date of the change both in the application and in the database

I sent you the address of the application on the email so you can take a look at the nature of the error

**Comment by lponiewierski** [comment]
Tested on macOS Sierra and Windows 10 and still can't reproduce this problem.
Even on package you send me, everything works fine.
Changing the time zone also does not affect anything.

**Comment by semirov** [comment]
There are suspicions that you did not understand the nature of the error

1) I create a master order, a production order or any other;
2) I specify the start date, end date, deadline
![image](https://user-images.githubusercontent.com/23023531/29120051-5ef4305a-7d11-11e7-817e-39b081fba706.png)

3) I press the save button and watch the time change in the fields start date, end date and other time fields.
![image](https://user-images.githubusercontent.com/23023531/29120104-87b57896-7d11-11e7-9b25-17edfac85856.png)

4) Each press of the save button results in subtracting one hour from all the time fields, even those that are not editable

![image](https://user-images.githubusercontent.com/23023531/29120183-dab69d90-7d11-11e7-99fd-e72ac6cc93d0.png)

**Comment by lponiewierski** [comment]
I'm glad you managed yourself.
