### ISSUE TITLE
Question about qcadoo mes installation

### ISSUE THREAD

**Issue by laindragon** [qcadoo/mes#18]
I have installed **qcadoo-mes-1.7.2**  following instruction, but I cannot use it.

I installed **jdk 8u 114** and **postgresql-9.6.4-1**.

 

However, in tomcat

error has occurred such as log4j error.

 

When I solved log4j error, by creating log4j.properties in WEB-INF\class directory

but it does not work (invoking afterpropertiesset() on bean with name).

How can I do?

**Comment by kmalyszek** [comment]
Hello,
could you give us additional information about error you are getting, and include log messages (from file root.log)?

**Comment by laindragon** [comment]
I attached file about error.

 My method to solve log4j error may be incorrect, so I only include log4j error

[logs.zip](https://github.com/qcadoo/mes/files/1229838/logs.zip)
![error in tomcat](https://user-images.githubusercontent.com/30743876/29391382-ebd6edfc-8331-11e7-99cd-577381dc8951.jpg)

**Comment by kmalyszek** [comment]
It looks like you have a problem with database schema - root.log shows errors such as: 
hibernate.HibernateException: Missing table: qcadooplugin_plugin
Please make sure you have correct database schema imported.
From installation manual:
"Before first run, You have to restore clean database schema that We provide with qcadoo MES package (mes-application/webapps/ROOT/WEB-INF/classes/schema/demo_db_en.sql). This is one of the conditions for qcadoo MES to work nice & smooth.
All You have to do is to restore this dump using the following command in BASH (assuming, You have installed postgreSQL as the user postgres, and created database mes with password postgres123):
psql -U postgres mes < path/to/schema/demo_db_en.sql"

**Comment by laindragon** [comment]
Frankly speaking, I cannot understand the line.

I don't know what is BASH in windows.
and "psql -U postgres mes < path/to/schema/demo_db_en.sql"

What I have tried are:

![psql1](https://user-images.githubusercontent.com/30743876/29410180-72464254-838a-11e7-83f1-641f12bb572e.JPG)

And

![psql2](https://user-images.githubusercontent.com/30743876/29410280-d8f27d24-838a-11e7-8d8f-2a193a5aa59e.JPG)

if possible, please explain by illustration.

Thank you.

**Comment by kmalyszek** [comment]
Download schema file from our repository, from directory
https://github.com/qcadoo/mes/tree/master/mes-application/src/main/resources/schema
After you save this file on your local machine, use in command line (like you tried before):
_psql -U postgres mes < path/to/schema/demo_db_en.sql_ - but replace **path/to/schema/demo_db_en.sql** with path to downloaded file, for example if you save schema on C:\Downloads, command would look like:
_psql -U postgres mes < C:\Downloads\demo_db_en.sql_

**Comment by laindragon** [comment]
Thank you for all your help

I tried and something happened (unknown letters)
but same error occurred.

![psql result](https://user-images.githubusercontent.com/30743876/29442725-5ba27354-840e-11e7-85b2-ce0391d25f22.JPG)

[logs.zip](https://github.com/qcadoo/mes/files/1233189/logs.zip)

**Comment by marcinperlak** [comment]
I think you have to find somebody that can help you with the PostgreSQL part of the installation (and general speaking DB installation). 
In the usage of qcadoo Community Edition there is required some level of basic knowledge of PostgreSQL and Tomcat. We can not support you in this.

**Comment by laindragon** [comment]
I succeeded by using startup.sh instead of startup.bat
