### ISSUE TITLE
mes-pack-open-source module

### ISSUE THREAD

**Issue by zh1314** [qcadoo/mes#20]
Hi, 
i don't know how does mes-pack-open-source module work.
it seems that it has no effect in this application.

so how it work or what role does it play in this system?

**Comment by lponiewierski** [comment]
Hi, 
this module was used as an aggregate for few other modules.
When you try to enable this plugin in Administration / Plug-ins, it will ask you if you want to enable it's dependencies. The list of them you can find in qcadoo-plugin.xml.
Currently we don't use it any more.
Regards.
