### ISSUE TITLE
Can not make action in this application

### ISSUE THREAD

**Issue by diliuhua** [qcadoo/mes#21]
Hello.
After i run  this application, just has a menu "Application". I can not make plan or do any action from the web page, can you tell me if something wrong of my deploy or useage?
Thank you very much.

**Comment by kmalyszek** [comment]
Hello, 
please try to log in to appliation as user "superadmin" with password "superadmin", then go to menu - "Administration" -> "Groups", and add all possible roles to group "Super admin". Log out and log in - you should be able to see other menu positions.
Let me know if this solves your problem.

**Comment by diliuhua** [comment]
Hello.
Thank your very much.
Wow, After follow your guidance，The menu has appeared. It is very complete and functional.
Finally, thank you for your careful answer.
