### ISSUE TITLE
How can I access data I made in qcadoo?

### ISSUE THREAD

**Issue by laindragon** [qcadoo/mes#24]
I made product data in qcadoo like picture below

![image](https://user-images.githubusercontent.com/30743876/31772047-398c0afa-b519-11e7-9327-3b40f3f362a7.png)

![image](https://user-images.githubusercontent.com/30743876/31772335-543fa16c-b51a-11e7-86dc-4d4264f97df6.png)

but I want access and input data by code.

is there any API?

**Comment by marcinperlak** [comment]
Hi, our API is available only in the commercial version of qcadoo MES
