### ISSUE TITLE
Debug with IDEA

### ISSUE THREAD

**Issue by shawn-show** [qcadoo/mes#27]
hi,i want to know how can i debug the qcadoo mes with IDEA?Before this version,we use jetty:run.But this version i see you dont use the jetty again?So how can i debug with IDEA

**Comment by krna** [comment]
We've removed jetty a couple months ago. To run qcadoo MES we use tomcat. You should build a package with tomcat. Run tomcat with debug options enabled and use Remote configurations in Run/Debug options with IDEA.
