### ISSUE TITLE
how to make two level linkage

### ISSUE THREAD

**Issue by shawn-show** [qcadoo/mes#29]
there are two selection options.When i change the first one,i want change the candidate items of the second one.we call this two level linkage.So how can i do that in qcadoo mes?

**Comment by krna** [comment]
You could use CriteriaModifier - there are many usage examples in mes.

**Comment by shawn-show** [comment]
en……can you get a url about CriteriaModifier ?

**Comment by krna** [comment]
https://qcadoo.atlassian.net/wiki/spaces/QCDMESDOC/pages/3375229/Hooks+and+Listeners#HooksandListeners-6.4.criteriamodifiers
