### ISSUE TITLE
how can i init my db?

### ISSUE THREAD

**Issue by shawn-show** [qcadoo/mes#30]
how can i insert myself dictionary and its items into the db when i  run the mes first time?

**Comment by krna** [comment]
You should define Your dictionary in some plugin qcadoo-plugin.xml file - for example <model:dictionary name="color"/>. Next you should write some loader to load your items for  example: https://github.com/qcadoo/mes/blob/master/mes-plugins/mes-plugins-basic/src/main/java/com/qcadoo/mes/basic/ColorLoader.java
