### ISSUE TITLE
how to change the text of tree node

### ISSUE THREAD

**Issue by shawn-show** [qcadoo/mes#32]
![1](https://user-images.githubusercontent.com/23192957/33638513-84135764-da61-11e7-9731-758335389b43.jpg)
I know that the text content of tree node is obtained from database. Now I want to change the content of text before I display the text of the node, for example, add some remarks, and without changing the original data of the database. In other words, how can I intercept the text and edit them before the node text is displayed .

**Comment by lponiewierski** [comment]
Hi,
if your're reffering to technologyDetails.xml, here's place where You can edit the content of the tree node:

https://github.com/qcadoo/mes/blob/master/mes-plugins/mes-plugins-technologies/src/main/resources/technologies/view/technologyDetails.xml#L316-L317

Regards.

**Comment by shawn-show** [comment]
I saw this code
` <option type="nodeLabelExpression"   value="#nodeNumber + ' &lt;span class=&quot;grey&quot;&gt;' + #operation['number'] + ' &lt;/span&gt;' + #operation['name']"/>`
But the expression is made up of fields in the database,what I want is that the text which will be replaced the expression is not in the db,but is depending on some fields.
In other words,I want to get the tree entities and edit its fields after them are queried from db and before them are showed on the page.
In addition,do you query the one to many fields just before the tree will be showed?Because when i get the model in hooks but the one to many fields is null...

**Comment by lponiewierski** [comment]
You can try use onView hook but we didn't tested this way.
Check how it's done here:

https://github.com/qcadoo/mes/blob/master/mes-plugins/mes-plugins-technologies/src/main/resources/technologies/view/technologyDetails.xml#L478-L519

and look at this class:

https://github.com/qcadoo/mes/blob/master/mes-plugins/mes-plugins-technologies/src/main/java/com/qcadoo/mes/technologies/tree/ProductStructureTreeService.java

maybe it will give You some ideas.
