### ISSUE TITLE
How can I solve the problem that technology tree is displayed incorrectly?

### ISSUE THREAD

**Issue by jsntlql** [qcadoo/mes#33]
Here, I found that the technology tree node is not correct and shows all null pointers, but I click on the process go in and can see the corresponding selected process, what will cause this situation, please help me, thank you!

![show incorrectly_meitu_2](https://user-images.githubusercontent.com/33685088/33694572-cdb2936c-db33-11e7-846c-3f8b519e05e8.jpg)

**Comment by lponiewierski** [comment]
Hi,
it looks like operation number and name are null.
Please try changing them, maybe some special characters are causing this situation.
As you can see in open issues it's not common situation.
Regards.
