### ISSUE TITLE
Will the list header can be combined?

### ISSUE THREAD

**Issue by superla** [qcadoo/mes#34]
![111111](https://user-images.githubusercontent.com/26450818/33701185-95bd0ba2-db58-11e7-87f9-a4a5d4b8247c.jpg)
See your framework feels very good, is your list can be merged header?
Just like the effect in the picture

**Comment by lponiewierski** [comment]
Hi,
if you refer to grid component it's not possible.
You can do this only in reports pdf or xls.
Regards.

**Comment by 731826971** [comment]
I see ,thank you for your answer.
