### ISSUE TITLE
About jqGrid

### ISSUE THREAD

**Issue by github-nbj** [qcadoo/mes#35]
Excause me,can you tell me about jquery.jqGrid.min.js version.
It really is 4.8.2？
How to get the jqGrid Table object in the XML(List View)?
$("#window_mainTab_foodList_grid").jqGrid('setGroupHeaders',{
		useColSpanStyle : true,
		groupHeaders: [
		{startColumnName:'price',
		numberOfColumns:3,
                titleText:'sumPrice'}]
		});
The console shows error message :"cannot evaluate script: jqGrid - No such method: setGroupHeaders".
Help me ,please ,thank you !

**Comment by lponiewierski** [comment]
Hi,
yes, we're using this version.

Please check the examples in jqGrid documentation:

http://www.trirand.com/blog/jqgrid/jqgrid.html

Regards.
