### ISSUE TITLE
How to package and run the project with tomcat?

### ISSUE THREAD

**Issue by jsntlql** [qcadoo/mes#36]
Hi , How to compile and run mes project , I found a similar closure in front of the closure, but I only understand remote debugging, for package the project into tomcat，what parameters or what command operation i need to set ? My development tool is idea. Can you take some pictures to show you steps?please,help me!
When tomcat started, there were some mistakes:
![123123123](https://user-images.githubusercontent.com/33685088/33865480-e2da67ea-df2c-11e7-80c6-65794ab90cce.jpg)
![234234](https://user-images.githubusercontent.com/33685088/33865513-0c9b19c6-df2d-11e7-89e3-5c43d9abe663.jpg)
 how to solve？

**Comment by lponiewierski** [comment]
Hi,
please check the documentation:

https://qcadoo.atlassian.net/wiki/spaces/QCDMESDOC/pages/29720742/Building+MES+from+source+code+-+tutorial

Regards.

**Comment by jsntlql** [comment]
Thanks for your reply!
