### ISSUE TITLE
cant run the tomcat with the latest version

### ISSUE THREAD

**Issue by shawn-show** [qcadoo/mes#37]
i just do anything step by step ,follow the document in [https://qcadoo.atlassian.net/wiki/spaces/QCDMESDOC/pages/29720742/Building+MES+from+source+code+-+tutorial](url),but when i start the tomcat it report the errors like 
![20171212102741](https://user-images.githubusercontent.com/23192957/33864416-80833108-df27-11e7-9942-97a8fbf3ca65.png)
Why????

**Comment by lponiewierski** [comment]
Hi,
these errors shouldn't cause the application to fail.  
We've got some problems in aspects and no time to fix that, maybe some day :)

Please see the warn.log and root.log from mes-application/logs/ folder.
Check if there are some errors.
Regards.
