### ISSUE TITLE
How to find the path  WEB-INF/jsp.xxx..jsp!

### ISSUE THREAD

**Issue by jsntlql** [qcadoo/mes#38]
Hi,I create a new plugins and  jsp file reference in the view species.But I cant find the jsp，the file path is correct. The mes version is 1.8 .Where do I need to configure the resource path?

**Comment by lponiewierski** [comment]
Hi,
search for occurences of _multiUpload.jsp_ and check how this static page was added.

Also add in qcadoo-plugin.xml:

`<view:resource uri="public/**/*"/>`

Regards.

**Comment by jsntlql** [comment]
In new plugins,the setting  <view:resource uri="public/**/*"/> exists,but I cant find the static page also.

**Comment by jsntlql** [comment]
I find two days for the setting about static page but no result. In  plugins "mes-plugin-technology" I cant find anything about the setting ,Can you speak more in detail? I'm almost crazy!

**Comment by lponiewierski** [comment]
Hi,
maybe this will be better example for your problem:

https://github.com/qcadoo/mes/blob/master/mes-plugins/mes-plugins-basic/src/main/resources/qcadoo-plugin.xml#L72

and:

https://github.com/qcadoo/mes/blob/master/mes-plugins/mes-plugins-basic/src/main/resources/qcadoo-plugin.xml#L278-L279

JSP file:

https://github.com/qcadoo/mes/blob/master/mes-plugins/mes-plugins-basic/src/main/resources/WEB-INF/jsp/basic/dashboard.jsp

Controller:

https://github.com/qcadoo/mes/blob/master/mes-plugins/mes-plugins-basic/src/main/java/com/qcadoo/mes/basic/DashboardController.java

Notice that, when you add new view it has to be added in database (check _qcadooview_view_ and _qcadooview_item_ tables, search records with name same as menu-item-url in qcadoo-plugin). Another way is to create clean database with _hibernateHbm2ddlAuto_ property set to _create_ in _db.properties_.
Regards.

**Comment by jsntlql** [comment]
Hi,Maybe you did not understand the problem I'm having now，I use “view.openModal(url)” to open a page.This  url is a  xxx.xml and it contains a static jsp page.I cant find the jsp path.I dont need  modelAndView.

**Comment by superla** [comment]
just for fun
