### ISSUE TITLE
edit the original field or component

### ISSUE THREAD

**Issue by shawn-show** [qcadoo/mes#39]
Hi,there are some model fields or view components in the mes original plugins which i dont need.Then i want to delete them by my plugins like
`
<model:model-field plugin="basic" model="product">
            <model:datetime name="lastMigrateTime"/>
        </model:model-field>
`
which can add field?So how can i delete or edit(like add unique)  the field ?

**Comment by lponiewierski** [comment]
Hi,
there is no possibility to delete fields from external plugins.
You have to do it in original plugin.
Regards.
