### ISSUE TITLE
can't run mes

### ISSUE THREAD

**Issue by zh1314** [qcadoo/mes#41]
the log in warn.log:

the keyword is :  Error creating bean with name 'receiptDocumentForReleaseHelper': Requested bean is currently in creation: Is there an unresolvable circular reference?

[localhost-startStop-1] WARN  org.springframework.web.context.support.XmlWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentsListListeners': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.nereus.mes.materialFlowResources.service.ReceiptDocumentForReleaseHelper com.nereus.mes.materialFlowResources.listeners.DocumentsListListeners.receiptDocumentForReleaseHelper; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'receiptDocumentForReleaseHelper' defined in URL [jar:file:/Users/zhanghui/skye.git/nereus/mes-application/webapps/ROOT/WEB-INF/lib/mes-plugins-material-flow-resources-1.5-SNAPSHOT.jar!/com/nereus/mes/materialFlowResources/service/ReceiptDocumentForReleaseHelper.class]: Unsatisfied dependency expressed through constructor argument with index 1 of type [com.nereus.mes.materialFlowResources.service.DocumentManagementService]: : Error creating bean with name 'documentManagementServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.nereus.mes.materialFlowResources.service.ReceiptDocumentForReleaseHelper com.nereus.mes.materialFlowResources.service.DocumentManagementServiceImpl.receiptDocumentForReleaseHelper; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'receiptDocumentForReleaseHelper': Requested bean is currently in creation: Is there an unresolvable circular reference?; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentManagementServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.nereus.mes.materialFlowResources.service.ReceiptDocumentForReleaseHelper com.nereus.mes.materialFlowResources.service.DocumentManagementServiceImpl.receiptDocumentForReleaseHelper; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'receiptDocumentForReleaseHelper': Requested bean is currently in creation: Is there an unresolvable circular reference?

**Comment by lponiewierski** [comment]
Hi,
this problem was fixed in new version which has just been released.
Regards.
