### ISSUE TITLE
How can I solve "0 use of ProceedingJoinPoint is allowed only on around advice "?

### ISSUE THREAD

**Issue by githubNICE** [qcadoo/mes#42]
Hi, these is an error in "catalina.out" file when I run the mes.
 l#noconfig for more info.
[ParallelWebappClassLoader@1870e7af] warning javax.* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified
[ParallelWebappClassLoader@1870e7af] warning no match for this type name: askForNotAcceptReason [Xlint:invalidAbsoluteTypeName]
[ParallelWebappClassLoader@1870e7af] error at com\qcadoo\mes\techSubcontrForOperTasks\aop\OperationalTaskHooksOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.hooks.OperationalTaskHooksOTFO.onSave(..)) && args(BindingTypePattern(com.qcadoo.model.api.DataDefinition, 1), BindingTypePattern(com.qcadoo.model.api.Entity, 2))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect.afterOnSaveExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.model.api.DataDefinition, com.qcadoo.model.api.Entity)))
[ParallelWebappClassLoader@1870e7af] error at com\qcadoo\mes\techSubcontrForOperTasks\aop\OperationalTaskHooksOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.hooks.OperationalTaskHooksOTFO.onSave(..)) && args(BindingTypePattern(com.qcadoo.model.api.DataDefinition, 1), BindingTypePattern(com.qcadoo.model.api.Entity, 2))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect.afterOnSaveExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.model.api.DataDefinition, com.qcadoo.model.api.Entity)))
[ParallelWebappClassLoader@1870e7af] error at com\qcadoo\mes\techSubcontrForOperTasks\aop\OperationalTaskDetailsListenersOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.listeners.OperationalTaskDetailsListenersOTFO.setOperationalTaskNameAndDescription(..)) && args(BindingTypePattern(com.qcadoo.view.api.ViewDefinitionState, 1), BindingTypePattern(com.qcadoo.view.api.ComponentState, 2), BindingTypePattern(java.lang.String[], 3))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect.afterSetOperationalTaskNameAndDescriptionExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.view.api.ViewDefinitionState, com.qcadoo.view.api.ComponentState, java.lang.String[])))
[ParallelWebappClassLoader@1870e7af] error at com\qcadoo\mes\techSubcontrForOperTasks\aop\OperationalTaskDetailsListenersOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.listeners.OperationalTaskDetailsListenersOTFO.setOperationalTaskNameAndDescription(..)) && args(BindingTypePattern(com.qcadoo.view.api.ViewDefinitionState, 1), BindingTypePattern(com.qcadoo.view.api.ComponentState, 2), BindingTypePattern(java.lang.String[], 3))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect.afterSetOperationalTaskNameAndDescriptionExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.view.api.ViewDefinitionState, com.qcadoo.view.api.ComponentState, java.lang.String[])))
log4j:WARN No appenders could be found for logger (org.springframework.web.context.ContextLoader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[ParallelWebappClassLoader@61cc09ba] warning javax.* types are not being woven because the weaver option '-Xset:weaveJavaxPackages=true' has not been specified
[ParallelWebappClassLoader@61cc09ba] warning no match for this type name: askForNotAcceptReason [Xlint:invalidAbsoluteTypeName]
[ParallelWebappClassLoader@61cc09ba] error at com\qcadoo\mes\techSubcontrForOperTasks\aop\OperationalTaskHooksOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.hooks.OperationalTaskHooksOTFO.onSave(..)) && args(BindingTypePattern(com.qcadoo.model.api.DataDefinition, 1), BindingTypePattern(com.qcadoo.model.api.Entity, 2))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect.afterOnSaveExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.model.api.DataDefinition, com.qcadoo.model.api.Entity)))
[ParallelWebappClassLoader@61cc09ba] error at com\qcadoo\mes\techSubcontrForOperTasks\aop\OperationalTaskHooksOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.hooks.OperationalTaskHooksOTFO.onSave(..)) && args(BindingTypePattern(com.qcadoo.model.api.DataDefinition, 1), BindingTypePattern(com.qcadoo.model.api.Entity, 2))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskHooksOTFOOverrideAspect.afterOnSaveExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.model.api.DataDefinition, com.qcadoo.model.api.Entity)))
[ParallelWebappClassLoader@61cc09ba] error at com\qcadoo\mes\techSubcontrForOperTasks\aop\OperationalTaskDetailsListenersOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.listeners.OperationalTaskDetailsListenersOTFO.setOperationalTaskNameAndDescription(..)) && args(BindingTypePattern(com.qcadoo.view.api.ViewDefinitionState, 1), BindingTypePattern(com.qcadoo.view.api.ComponentState, 2), BindingTypePattern(java.lang.String[], 3))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect.afterSetOperationalTaskNameAndDescriptionExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.view.api.ViewDefinitionState, com.qcadoo.view.api.ComponentState, java.lang.String[])))
[ParallelWebappClassLoader@61cc09ba] error at com\qcadoo\mes\techSubcontrForOperTasks\aop\OperationalTaskDetailsListenersOTFOOverrideAspect.java::0 use of ProceedingJoinPoint is allowed only on around advice (arg 0 in (after(extraFlags: 2): ((execution(public void com.qcadoo.mes.operationalTasksForOrders.listeners.OperationalTaskDetailsListenersOTFO.setOperationalTaskNameAndDescription(..)) && args(BindingTypePattern(com.qcadoo.view.api.ViewDefinitionState, 1), BindingTypePattern(com.qcadoo.view.api.ComponentState, 2), BindingTypePattern(java.lang.String[], 3))) && persingleton(com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect))->void com.qcadoo.mes.techSubcontrForOperTasks.aop.OperationalTaskDetailsListenersOTFOOverrideAspect.afterSetOperationalTaskNameAndDescriptionExecution(org.aspectj.lang.ProceedingJoinPoint, com.qcadoo.view.api.ViewDefinitionState, com.qcadoo.view.api.ComponentState, java.lang.String[])))

**Comment by marcinperlak** [comment]
Hi, we need more data what version od qcadoo MES are you running and on what environment.

**Comment by githubNICE** [comment]
Hi, I used the "master" version cloned  from "https://github.com/qcadoo/mes.git" two days ago. The environment is the following:
OS: window 10-x64
Java Jdk: jdk-8u152-windows-x64
apache-maven-3.5.2 and apache-tomcat-8.0.50
DB: postgresql-9.5.10-2

**Comment by lponiewierski** [comment]
Hi, 
look at this issue: https://github.com/qcadoo/mes/issues/37.

**Comment by githubNICE** [comment]
Thanks. But I find another error which may stop mes running. 

2018-02-27 21:34:54,000 [localhost-startStop-1] INFO  org.hibernate.dialect.Dialect - Using dialect: org.hibernate.dialect.PostgreSQLDialect
2018-02-27 21:34:54,029 [localhost-startStop-1] INFO  org.hibernate.engine.jdbc.JdbcSupportLoader - Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
2018-02-27 21:34:54,029 [localhost-startStop-1] INFO  org.hibernate.cfg.SettingsFactory - Database ->
       name : PostgreSQL
    version : 9.5.10
      major : 9
      minor : 5
2018-02-27 21:34:54,030 [localhost-startStop-1] INFO  org.hibernate.cfg.SettingsFactory - Driver ->
       name : PostgreSQL Native Driver
    version : PostgreSQL 9.4.1212
      major : 9
      minor : 4
Pls help me.

**Comment by lponiewierski** [comment]
Hi, 
it's only INFO message, please send full root.log or warn.log, otherwise we won't be able to help you.
Regards.
