### ISSUE TITLE
PLC Qcadoo

### ISSUE THREAD

**Issue by salwaalem** [qcadoo/mes#49]
Hi,

I'm contacting you to ask help. I'm a PhD student and I want to integrate Qcadoo with a PLC or a SCADA

I install Qcadoo under ubuntu and I want to Install a PLC to track the network traffic between Qcadoo and this PLC. Do you have any idea to how to do please ?

Thanks in advance for your help

Salwa

**Comment by marcinperlak** [comment]
Qcadoo doesn't have out of the box connection to PLC. You have to do it on your own, by writing i.e. new plugin in qcadoo with WebServices to exchange the data.
