### ISSUE TITLE
Qcadoo database

### ISSUE THREAD

**Issue by salwaalem** [qcadoo/mes#50]
Hello,

I wanto to know if Qcadoo can work with another Database like SQLEXPRESS (Bizagi) ?

Thanks in advance for your response.

Best regards

**Comment by lponiewierski** [comment]
Hi,
we didn't need to use this database so it's hard to tell.
For sure it works with Postgres and Oracle (with some minor changes).

Qcadoo uses Hibernate 3.6.9.Final, if it supports this database I think it should be possible.
Probably you will need to configure data source and use proper driver for SQLEXPRESS database.
Regards.
