### ISSUE TITLE
Issue with english installation documentation

### ISSUE THREAD

**Issue by maxthedude** [qcadoo/mes#51]
Hello, 
after I followed the installation manual and I think you have a slight issue in there. 
The import of the db dump has to happen as the postgres linux user as shown in the screenshot. If you execute the commands as stated you end up in the psql console where the import will not work. 
So only - sudo su postgres - would be the correct command that allows you to perform the next command to run successfully. 

Sorry I am opening an issue for this as it may not be of concern with the source code but I couldn't find any other place to post this. 

Cheers

**Comment by lponiewierski** [comment]
Hi,
thanks for noticing.
Regards.
