### ISSUE TITLE
Exception while save data

### ISSUE THREAD

**Issue by jsntlql** [qcadoo/mes#54]
Thanks for help me：
       Now，I have a distressed thing，the annotation ‘@Transactional’ can not catch the errors where happened when save data.the errors in the 'getErrors()' can not  throw outside. The action 'DataDefinition.save(entity)' is so much,The amount of code is too large.
      Is there a good way to help me solve this problem?
Best wish！

**Comment by lponiewierski** [comment]
Hi, 
you can add missing translations to properties files or send us correct keys with apropiate values
and we'll include them in new version.
Regards.

**Comment by lponiewierski** [comment]
Hi,
it hard to tell what's the problem without seeing code.
Could you give us more details?
Regards.
